name: Hello World Workflow

on:
  push:
    branches: [ main ]

jobs:
  greeting:
    runs-on: [my-laptop]

    steps:
    - name: Say Hello
      run: echo "Hello, World! ğŸ‘‹ Ini deployment pertama saya dari GitHub Actions!"

    - name: Show Date and Time
      run: echo "Current time is $(date) â±ï¸"
